### ISSUE TITLE
Atribuir uma licença Creative Commons ao site

### ISSUE THREAD

**Issue by barrosgeraldo** [WoMakersCode/womakerscode.github.io#1]
- [x] Definir uma licença para o site;
- [x] Adicionar a licença no footer do site.

---
Partes deste conteúdo possuem direitos reservados (©2015–2017) por colaboradores da womakerscode.org. [Conteúdo disponível sob a licença Creative Commons](https://br.creativecommons.org/licencas/).

**Comment by cyz** [comment]
aplicado e disponível na branch develop :)

**Comment by barrosgeraldo** [comment]
@cyz, acho que só faltou o link para uma licença, acredito que essa é ótima: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.pt_BR.
