### ISSUE TITLE
Imagem com overflow

### ISSUE THREAD

**Issue by cynthiapereira** [WoMakersCode/womakerscode.github.io#2]
A imagem na lateral direita da `<section class="area">` ultrapassa o overflow com um width superior à 1200 pixels.

https://github.com/WoMakersCode/womakerscode.github.io/blob/master/index.html#L117

Navegador testados: 
- Mozilla Firefox for Ubuntu 43.0b4  (64-bit)
- Google Chrome Versão 46.0.2490.86 (64-bit)

![bug](https://cloud.githubusercontent.com/assets/1923666/11278781/15c2ba00-8ed4-11e5-8204-6030115918cc.png)

**Comment by cyz** [comment]
done
